### ISSUE TITLE
Scrollbar issue with latest version of Datawidgets Datagrid2

### ISSUE THREAD

**Issue by LokeshReddyT** [bsgriggs/mendix-controllable-tab-container#6]
Hi there, 
Recently i try to update the datawidgets to latest version ie. V.2.18.0. I noticed an issue that after updating, Datagrid2 is automatically scrolling to the right side by default. I didn't see the issue with default tab container. I tried from the datawidgets  V.2.15.0 to V.2.18.0. But i still face same issue where datagrid2 is automatically scrolling to right.  In the application it is showing the scroll at left by default. But when we switch between tabs then scrollbar is auto scrolling to right side.

![Screenshot 2024-04-30 190150](https://github.com/bsgriggs/mendix-controllable-tab-container/assets/63348842/97a8133a-cfeb-4c36-80b6-58c00bb9edb8)
![Screenshot 2024-04-30 190125](https://github.com/bsgriggs/mendix-controllable-tab-container/assets/63348842/a9b2ed21-346d-495c-80b5-f0ffa8c7bce4)
![Screenshot 2024-04-30 185559](https://github.com/bsgriggs/mendix-controllable-tab-container/assets/63348842/913db620-d98c-4365-928c-680797f63f21)

 Could you please check is it possible to fix?
Thanks in Advance.

**Comment by bsgriggs** [comment]
Hi there,
This is working as intended. You're setting the columns to have a **minimum** width of 500px. With 5 columns that's 2500px and larger than most screen sizes.

**Comment by LokeshReddyT** [comment]
Hi Benjamin, 
Thanks for the explanation. But before updating the datawidgets to the latest version. We are using v.2.11.0 previously. In that version the option min width is not their for Auto fit content. So i used to set the width directly to the data grid 2 under style option. There even though i set width to 3000px, It will show a scrollbar to scroll through the data grid 2. But in that version i didn't see the issue where scrollbar auto scroll to right side when switching between tabs. In v.2.11.0 of Data widgets the scroll bar is showing at left side by default. I tried with setting column width to auto and datagrid2 with to 3000px as well in latest version. But that also scrolling to right side. I am not good in css and not sure how it exactly different from both scenarios. Could you please help me with this.

**Comment by LokeshReddyT** [comment]
Hi Benjamin,

Could you please confirm the above whether it is still the intended behavior?. 
Thanks in advance. 

Best Regards, 
Lokesh.

**Comment by bsgriggs** [comment]
It looks like the dg2 filters are stealing focus for some reason. I can look into it.

**Comment by bsgriggs** [comment]
This is not an issue with the Controllable Tab Container but with the data filter widgets. This issue is reproducible any time a data grid 2 or gallery widget is completely removed from the UI and re-added. The most common use-case for this is a visibility condition.

Example: https://widgettesting105-sandbox.mxapps.io/p/dg2testing
DG2 is removed via visible = false

![Screenshot 2024-05-23 at 11 31 00 AM](https://github.com/bsgriggs/mendix-controllable-tab-container/assets/47681665/8774bfb8-212c-454e-9b6f-1be447de479e)

When visible is switched to true, one of the last filter widgets is auto-focused. If this input is off the side of the screen that forces the scrollbar to move. 
![Screenshot 2024-05-23 at 11 30 56 AM](https://github.com/bsgriggs/mendix-controllable-tab-container/assets/47681665/402146cb-e461-42c8-ae54-8b64a863598a)

The code responsible is _likely_ a utility file below. **inputRef.current?.focus();** 
https://github.com/mendix/web-widgets/blob/851666cb41a9a64d707f1764a8281e570b560e2a/packages/shared/widget-plugin-filtering/src/controls/input/useInputProps.ts#L41

I am not associated with R&D, so I cannot fix this issue. I would recommend submitting a bug report through Mendix support: https://support.mendix.com/hc/en-us/requests/new
